# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.211.0"

default_platform(:android)

# App Center
APP_CENTER_API_TOKEN            = ENV["APP_CENTER_API_TOKEN"]
APP_CENTER_OWNER_NAME           = ENV["APP_CENTER_OWNER_NAME"]
APP_CENTER_APP_NAME             = ENV["APP_CENTER_APP_NAME"]

platform :android do
  
  desc "build android apk"
  lane :build do
    flutter_build(
      build: "apk",
      # build_number: {buildNumber}
    )
  end

  desc "upload android apk to app center"
  lane :upload_to_appcenter do
    # Upload the app
    file = '../build/app/outputs/bundle/release/app-release.aab'
    appcenter_upload(
      api_token: APP_CENTER_API_TOKEN,
      owner_name: APP_CENTER_OWNER_NAME,
      app_name: APP_CENTER_APP_NAME,
      # destinations: options[:groups],
      # release_notes: (options[:scheme].include? "Release") ? "RELEASE Build\n=============" : "DEBUG Build\n===========",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      file: '../build/app/outputs/apk/release/app-release.apk', # path of the apk that was built for upload
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end
end
